### ISSUE TITLE
should we keep or discard the contact form?

### ISSUE THREAD

**Issue by Anupam-dagar** [fossiiita/fossiiita.github.io#10]
we can use flipmail to make it functionable but all the form inputs will be sent to an email id.

**Comment by aswanthkoleri** [comment]
I think it's not needed !

**Comment by vsvipul** [comment]
same here, not required i think... can i remove it ?

**Comment by Anupam-dagar** [comment]
@vsvipul yes,remove it.

**Comment by vsvipul** [comment]
removed !
