### ISSUE TITLE
Slideshow images.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossiiita/fossiiita.github.io#2]
Currently there are photography images on slideshow,suggestions for suitable images is needed.
![screenshot from 2017-05-22 12-12-50](https://cloud.githubusercontent.com/assets/21174572/26295552/08e98460-3ee8-11e7-80d0-0d14a6811f4c.png)

**Comment by aswanthkoleri** [comment]
Some Photos from IIITA Hacks would be nice i guess @Anupam-dagar  ! .

**Comment by Anupam-dagar** [comment]
I think some minimalistic images will look more better.
Photos from IIITA hacks will make it look like an event page.
You can give it a try.

**Comment by Anupam-dagar** [comment]
done
