### ISSUE TITLE
Make coordinators section compact

### ISSUE THREAD

**Issue by vsvipul** [fossiiita/fossiiita.github.io#20]
See if the two coordinators can be shown side by side as in members, while keeping the design maintained...

**Comment by Anupam-dagar** [comment]
It can be done easily but we have to show bio also, I will do that and post a screenshot over here. I don't think it will look good.

**Comment by vsvipul** [comment]
u can try it

**Comment by Anupam-dagar** [comment]
i don't think this looks good, as we have only 12 columns, this only looks the most suitable way.
Also there is no place to add a bio. Other way can be if we replace coordinators card with the members one but then everything will look similar as resources also use members card.
![screenshot from 2017-06-09 13-39-45](https://user-images.githubusercontent.com/21174572/26966793-383e8096-4d19-11e7-8b58-868e5b65dbfd.png)

**Comment by vsvipul** [comment]
cant we make it look like the members cards? those look better than this... and a small bio will be just fine... ?

**Comment by Anupam-dagar** [comment]
Ok, I will post a screenshot of it.
