### ISSUE TITLE
Add GSOC section as a second slide to the home section

### ISSUE THREAD

**Issue by vsvipul** [fossiiita/fossiiita.github.io#21]
Remove the gsoc section and add the achievement (13 selections) as a slide to in the home section.

Make it a slideshow to alternate between the current home and the achievement..

**Comment by Anupam-dagar** [comment]
I didn't get this, how do you want to show it, can you show an example.

**Comment by vsvipul** [comment]
https://vsvipul.github.io/
see how the text changes in home section... just add "13 people selected in gsoc" like that in foss home section !

**Comment by gauthamzz** [comment]
I might suggest putting all the gsoc peoples info here . like make fossiiita.github.io/gsoc page and add all images in a place. would be much cooler . https://github.com/fossiiita/gsoc 

It was already made for that , but we didnt finish it at that time

**Comment by Anupam-dagar** [comment]
This sounds much better.

**Comment by vsvipul** [comment]
yeah we can make that... and link it from foss page ! remove the gsoc section from main page ?? @Anupam-dagar

**Comment by Anupam-dagar** [comment]
yes, we should first create the page and then remove the section.

**Comment by gauthamzz** [comment]
when its made could we integrate it to the gsoc selections post in nybles by it too

**Comment by Anupam-dagar** [comment]
yes, should we make a page with complete different design from the template or it should be similar to template

**Comment by vsvipul** [comment]
page is made, integrating it now

**Comment by vsvipul** [comment]
made separate page.. closed
