### ISSUE TITLE
spacing between social media icons in coordinator section.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossiiita/fossiiita.github.io#7]
Increase spacing between social media icons and take icons a little lower.

**Comment by aswinzz** [comment]
![screenshot from 2017-05-23 00-27-37](https://cloud.githubusercontent.com/assets/25057819/26324007/aa3753f4-3f4e-11e7-83c1-cae6e0a1b946.png)
is this fine?

**Comment by Anupam-dagar** [comment]
Yeah,just take it down at the black mark.
![screenshot](https://cloud.githubusercontent.com/assets/21174572/26324286/d183227a-3f4f-11e7-8fc4-ab7542c0bf60.png)

**Comment by vsvipul** [comment]
this is fixed now.. !
